// @vitest-environment jsdom
import React from 'react';
import {cleanup,fireEvent,render,screen,within} from '@testing-library/react';
import {afterEach,describe,expect,it} from 'vitest';
import {DecisionCenterView,type DecisionCenterData} from '@/components/decision-center-live';
import type {Q3ExecutiveDecision} from '@/lib/q3/decisions';

const decision=(classification:Q3ExecutiveDecision['classification'],id:string,overrides:Partial<Q3ExecutiveDecision>={}):DecisionCenterData['decisions'][number]=>({id,classification,severity:classification==='EXECUTIVE_DECISION'?'HIGH':'ATTENTION',initiativeReference:`DSP-${id}`,initiativeName:`Iniciativa ${id}`,eco:'Personas',initiativeType:'STRATEGIC',pipelineStage:'RISK_GATE',blocked:false,replanningStatus:'REPLANNED_DATE_AND_QUARTER',carryOverStatus:'ADMINISTERED_CARRY_OVER',urgency:'OVERDUE',reason:'Existe evidencia que requiere revisión.',impact:'El gate impide avanzar en el pipeline.',recommendedAction:'Resolver el escalamiento y confirmar el compromiso.',alternatives:classification==='EXECUTIVE_DECISION'?['Resolver aprobación','Revisar compromiso']:[],evidence:[{metric:'Risk Gate',value:'En curso',entity:`DSP-${id}`,period:'Q3',source:'Jira LIVE',lastUpdated:'2026-08-22',coverage:100}],ruleId:classification==='DATA_QUALITY'?'INSUFFICIENT_EVIDENCE':'TEST_RULE',decisionOwnerRole:'VP / C-Level',targetDate:'2026-08-14',daysToTarget:-8,confidence:'HIGH',sourceSnapshotVersion:12,href:`/initiatives/DSP-${id}`,evidenceContext:{features:{completed:2,total:2},riskGateStatus:'IN_PROGRESS',riskDomains:{total:5,approved:2,applicable:5},previousTargetDate:'2026-07-31',targetDateChangeCount:3,quarterChangeCount:2},...overrides});
const data=(items:DecisionCenterData['decisions']):DecisionCenterData=>({snapshot:{version:12,lastUpdated:'2026-08-22T00:42:57.617Z'},source:'Jira LIVE',decisions:items});
afterEach(cleanup);

describe('Decision Center LIVE presentation',()=>{
 it('renders Decision before Attention',()=>{const{container}=render(<DecisionCenterView data={data([decision('EXECUTIVE_ATTENTION','2'),decision('EXECUTIVE_DECISION','1')])}/>);const required=container.querySelector('[data-testid="executive-decision"]')!,attention=container.querySelector('[data-testid="executive-attention"]')!;expect(required.compareDocumentPosition(attention)&Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy()});
 it('keeps Operational and Data Quality collapsed by default',()=>{render(<DecisionCenterView data={data([decision('OPERATIONAL_ACTION','3'),decision('DATA_QUALITY','4')])}/>);expect(screen.getByTestId('operational-collapsed').hasAttribute('open')).toBe(false);expect(screen.getByTestId('quality-collapsed').hasAttribute('open')).toBe(false);expect(screen.getByText('Gestión operativa')).toBeTruthy();expect(screen.getByText('Calidad de datos')).toBeTruthy()});
 it('does not expose technical enums, custom fields or metric plumbing',()=>{const{container}=render(<DecisionCenterView data={data([decision('EXECUTIVE_DECISION','1')])}/>);const text=container.textContent??'';expect(text).not.toContain('REPLANNED_DATE_AND_QUARTER');expect(text).not.toContain('EXECUTIVE_DECISION');expect(text).not.toContain('customfield_');expect(text).not.toContain('AVAILABLE');expect(text).not.toContain('PARTIAL');expect(screen.getByText('Fecha y trimestre replanificados')).toBeTruthy()});
 it('shows alternatives and owner role for a required Decision',()=>{render(<DecisionCenterView data={data([decision('EXECUTIVE_DECISION','1')])}/>);expect(screen.getByText('Resolver aprobación')).toBeTruthy();expect(screen.getByText('Revisar compromiso')).toBeTruthy();expect(screen.getByText('VP / C-Level')).toBeTruthy()});
 it('opens the evidence drill-down with semantic, sanitized facts',()=>{render(<DecisionCenterView data={data([decision('EXECUTIVE_DECISION','1')])}/>);const details=screen.getByText('Ver evidencia').closest('details')!;expect(details.hasAttribute('open')).toBe(false);fireEvent.click(within(details).getByText('Ver evidencia'));expect(details.hasAttribute('open')).toBe(true);expect(within(details).getByText('2/2 completadas')).toBeTruthy();expect(within(details).getByText('3 cambios de fecha · 2 de trimestre')).toBeTruthy()});
 it('preserves RBAC-safe aliases without introducing real names or ids',()=>{const{container}=render(<DecisionCenterView data={data([decision('EXECUTIVE_DECISION','001',{initiativeName:'DSP-001',initiativeReference:'DSP-001',href:'/decisions',evidence:[{metric:'Escalamiento ejecutivo',value:'Evidencia disponible',entity:'DSP-001',period:'Q3',source:'Jira LIVE',lastUpdated:'2026-08-22',coverage:100}]})])}/>);const text=container.textContent??'';expect(text).toContain('DSP-001');expect(text).not.toContain('Nombre sensible');expect(text).not.toContain('accountId');expect(text).not.toContain('customfield_')});
 it('accepts zero Decisions as a valid state',()=>{render(<DecisionCenterView data={data([decision('EXECUTIVE_ATTENTION','2')])}/>);expect(screen.getByText('No hay decisiones ejecutivas pendientes')).toBeTruthy();expect(document.querySelector('.dc-headline')?.textContent).toContain('0 decisiones requieren intervención')});
 it('supports multiple Decisions without collapsing them',()=>{const{container}=render(<DecisionCenterView data={data([decision('EXECUTIVE_DECISION','1'),decision('EXECUTIVE_DECISION','2')])}/>);expect(container.querySelectorAll('[data-testid="executive-decision"]')).toHaveLength(2);expect(document.querySelector('.dc-headline')?.textContent).toContain('2 decisiones requieren intervención')});
 it('uses bounded responsive containers instead of page-level overflow',()=>{const{container}=render(<DecisionCenterView data={data([decision('EXECUTIVE_ATTENTION','2')])}/>);expect(container.querySelector('.decision-center-live')).toBeTruthy();expect(container.querySelector('.dc-table-wrap')).toBeTruthy();expect(container.querySelector('[style*="min-width"]')).toBeNull()});
});
