import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {JiraCloudClient,JiraCloudError} from '@/lib/jira/client';
import {discoverJira,normalizeIssue,normalizeJiraStatus} from '@/lib/jira/live';
import {requireAdmin} from '@/lib/auth/server-session';

const credentials={baseUrl:'https://example.atlassian.net',email:'user@example.com',token:'super-secret-token',projects:['PAY'],maxIssues:2};
const json=(body:unknown,status=200,headers:Record<string,string>={})=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json',...headers}});
const issue=(key:string,status='In Progress')=>({key,fields:{summary:`Issue ${key}`,project:{key:'PAY',name:'Payments'},issuetype:{name:'Task'},status:{name:status},created:'2026-01-01',updated:'2026-01-02',labels:[]}});

describe('Jira Cloud LIVE read-only',()=>{
  beforeEach(()=>{vi.useFakeTimers({shouldAdvanceTime:true});vi.stubEnv('NODE_ENV','development')});afterEach(()=>{vi.useRealTimers();vi.unstubAllEnvs();vi.restoreAllMocks()});
  it('connects successfully without exposing Authorization',async()=>{const fetcher=vi.fn(async(_url:RequestInfo|URL,init?:RequestInit)=>{expect(init?.method).toBe('GET');expect(init?.headers).toHaveProperty('Accept','application/json');return json({accountId:'abc',displayName:'Flow User'})});const result=await new JiraCloudClient(credentials,fetcher as typeof fetch).getCurrentUser();expect(result.data.displayName).toBe('Flow User');expect(JSON.stringify(result)).not.toContain(credentials.token)});
  it.each([[401,'Las credenciales de Jira no son válidas o expiraron.'],[403,'FlowOS se autenticó, pero la cuenta no tiene acceso suficiente.']])('sanitizes HTTP %s',async(status,message)=>{const client=new JiraCloudClient(credentials,vi.fn(async()=>json({},status)) as typeof fetch);await expect(client.getCurrentUser()).rejects.toMatchObject({status,message});try{await client.getCurrentUser()}catch(error){expect(JSON.stringify(error)).not.toContain(credentials.token);expect(JSON.stringify(error)).not.toContain(credentials.email)}});
  it('retries 429 honoring Retry-After',async()=>{const fetcher=vi.fn().mockResolvedValueOnce(json({},429,{'retry-after':'0.001'})).mockResolvedValueOnce(json({ok:true}));await expect(new JiraCloudClient(credentials,fetcher).getServerInfo()).resolves.toMatchObject({data:{ok:true}});expect(fetcher).toHaveBeenCalledTimes(2)});
  it('retries a 500 response',async()=>{const fetcher=vi.fn().mockResolvedValueOnce(json({},500)).mockResolvedValueOnce(json({ok:true}));await new JiraCloudClient(credentials,fetcher).getServerInfo();expect(fetcher).toHaveBeenCalledTimes(2)});
  it('reports timeouts safely',async()=>{const fetcher=vi.fn((_url:RequestInfo|URL,init?:RequestInit)=>new Promise<Response>((_resolve,reject)=>init?.signal?.addEventListener('abort',()=>reject(new DOMException('aborted','AbortError')))));const promise=new JiraCloudClient(credentials,fetcher as typeof fetch,5).getServerInfo();const rejection=expect(promise).rejects.toMatchObject({code:'JIRA_TIMEOUT'});await vi.advanceTimersByTimeAsync(10);await rejection});
  it('uses cursor pagination and marks truncation at configured limit',async()=>{const fetcher=vi.fn().mockResolvedValueOnce(json({issues:[issue('PAY-1')],nextPageToken:'next',isLast:false})).mockResolvedValueOnce(json({issues:[issue('PAY-2')],nextPageToken:'more',isLast:false}));const page=await new JiraCloudClient(credentials,fetcher).searchIssues('project in ("PAY")',['summary'],2);expect(page.items).toHaveLength(2);expect(page.pagesProcessed).toBe(2);expect(page.truncated).toBe(true)});
  it('continues discovery when a field and project are inaccessible',async()=>{const client={getProjects:async()=>({items:[{key:'PAY'}]}),getFields:async()=>({data:[{id:'customfield_10064'}]}),getStatuses:async()=>({data:[]}),getIssueTypes:async()=>({data:[]})} as unknown as JiraCloudClient;const result=await discoverJira(client,['PAY','NOPE']);expect(result.projectsInaccessible).toEqual(['NOPE']);expect(result.fields.find(x=>x.id==='customfield_10020')?.status).toBe('MISSING');expect(result.warnings[0]).toContain('INACCESSIBLE')});
  it('normalizes source status and preserves it',()=>{const mapped=normalizeIssue(issue('PAY-1','Bloqueado'),credentials.baseUrl);expect(mapped).toMatchObject({sourceStatus:'Bloqueado',normalizedStage:'BLOCKED',sourceKey:'PAY-1'});expect(mapped.flagged.value).toBe(true);expect(normalizeJiraStatus('Masificación 99%')).toBe('MASSIFICATION')});
  it('preserves missing story-point evidence explicitly',()=>{const mapped=normalizeIssue(issue('PAY-1'),credentials.baseUrl);expect(mapped.storyPoints).toEqual({state:'MISSING',value:null})});
  it('allows demo ADMIN for snapshot authorization in development',()=>{expect(requireAdmin(new Request('http://local',{headers:{cookie:'flowos_demo_session=admin'}}))).toBe(true)});
  it('rejects demo ADMIN for snapshot authorization in production',()=>{vi.stubEnv('NODE_ENV','production');expect(requireAdmin(new Request('http://local',{headers:{cookie:'flowos_demo_session=admin'}}))).toBe(false)});
  it('rejects Executive snapshot authorization',()=>{expect(requireAdmin(new Request('http://local',{headers:{cookie:'flowos_demo_session=executive'}}))).toBe(false)});
  it.each([undefined,'flowos_demo_session=arbitrary','unrelated=admin'])('rejects a missing or arbitrary cookie',cookie=>{const headers=typeof cookie==='string'?{cookie}:undefined;expect(requireAdmin(new Request('http://local',{headers}))).toBe(false)});
  it('keeps DEMO fallback explicit when there is no LIVE snapshot',()=>{const fallback={dataMode:'DEMO',available:false};expect(fallback).toEqual({dataMode:'DEMO',available:false})});
  it('never permits mutating HTTP methods',async()=>{const fetcher=vi.fn(async(_url:RequestInfo|URL,init?:RequestInit)=>json({method:init?.method}));await new JiraCloudClient(credentials,fetcher as typeof fetch).getProject('PAY');expect(fetcher.mock.calls[0][1]?.method).toBe('GET')});
  it('returns a typed sanitized error for network failures',async()=>{const client=new JiraCloudClient(credentials,vi.fn(async()=>{throw new Error(`failed ${credentials.token}`)}) as typeof fetch,10,0);await expect(client.getServerInfo()).rejects.toBeInstanceOf(JiraCloudError);await expect(client.getServerInfo()).rejects.toMatchObject({message:'No fue posible conectar con Jira Cloud.'})});
});
