import {describe,expect,it,vi} from 'vitest';
import type {JiraCloudClient,JiraPage} from '@/lib/jira/client';
import type {JiraCredentials} from '@/lib/jira/credentials';
import {acquireQ3Datasets} from '@/lib/q3/acquisition';
import {Q3_REQUIRED_FIELDS,Q3_PROFILE_VERSION} from '@/lib/q3/config';
import {normalizeIssue} from '@/lib/jira/live';
import type {SemanticJiraSnapshotRecord} from '@/lib/jira/store';
import {buildQ3Overview} from '@/lib/q3/model';

const credentials:JiraCredentials={baseUrl:'https://site',email:'hidden@example.com',token:'hidden',projects:['DSP','CPD','EMD'],maxIssues:500};
const page=(items:Record<string,unknown>[],truncated=false):JiraPage<Record<string,unknown>>=>({items,pagesProcessed:1,truncated,partial:false,warnings:[],correlationId:'safe',durationMs:1});
const raw=(key:string,project='DSP',type='Iniciativa estratégica',extra:Record<string,unknown>={})=>({key,fields:{summary:'Sensitive',project:{key:project},issuetype:{name:type},status:{name:'En desarrollo'},created:'2026-01-01',updated:'2026-08-01',labels:[],issuelinks:[],customfield_12634:[{name:'Q3'}],customfield_11944:'2026-09-15',...extra}});
const polaris=(key:string)=>({type:{id:'10006',outward:'is implemented by'},outwardIssue:{key,fields:{issuetype:{name:'Epic'}}}});
const catalog=Q3_REQUIRED_FIELDS.map(id=>({id,name:`Safe ${id}`,schema:{type:'string'}}));
function client(handler?:(jql:string,fields:string[],limit:number)=>Promise<JiraPage<Record<string,unknown>>>){const calls:Array<{jql:string;limit:number}>=[];const search=vi.fn(async(jql:string,fields:string[],limit:number)=>{calls.push({jql,limit});if(handler)return handler(jql,fields,limit);if(jql.includes('cf[12634]'))return page([raw('DSP-1')]);if(jql.startsWith('project in'))return page(Array.from({length:500},(_,i)=>raw(`CPD-${i}`,'CPD','Tarea')),true);return page([])});return {value:{getFields:async()=>({data:catalog}),searchIssues:search} as unknown as JiraCloudClient,calls}}
describe('Q3 dataset acquisition',()=>{
  it('runs portfolio and control before operational',async()=>{const fake=client();await acquireQ3Datasets(fake.value,credentials);expect(fake.calls[0].jql).toContain('project = DSP');expect(fake.calls[1].jql).toContain('project = DSP');expect(fake.calls.findIndex(x=>x.jql.startsWith('project in'))).toBeGreaterThan(1)});
  it('does not apply operational limit 500 to portfolio',async()=>{const fake=client();await acquireQ3Datasets(fake.value,credentials);expect(fake.calls[0].limit).toBe(Number.MAX_SAFE_INTEGER);expect(fake.calls.find(x=>x.jql.startsWith('project in'))?.limit).toBe(500)});
  it('distinguishes empty fields from fields missing in response',async()=>{const sample=raw('DSP-1','DSP','Iniciativa estratégica',{customfield_12634:[],customfield_11944:undefined});const fake=client(async jql=>jql.includes('cf[12634]')?page([sample]):page([]));const result=await acquireQ3Datasets(fake.value,credentials);expect(result.fieldSample.customfield_12634).toBe('EMPTY');expect(result.fieldSample.customfield_11944).toBe('EMPTY');expect(result.fieldSample.customfield_11372).toBe('MISSING_FROM_RESPONSE')});
  it('does not query portfolio when required query fields are missing',async()=>{const fake=client();(fake.value as unknown as {getFields:()=>unknown}).getFields=async()=>({data:catalog.filter(x=>x.id!=='customfield_12634')});const result=await acquireQ3Datasets(fake.value,credentials);expect(result.portfolio.status).toBe('UNAVAILABLE');expect(fake.calls.some(x=>x.jql.includes('cf[12634]'))).toBe(false)});
  it('expands multiple Polaris parents outside operational sample',async()=>{const initiative=raw('DSP-1','DSP','Iniciativa estratégica',{issuelinks:[polaris('CPD-1'),polaris('EMD-1')]});const fake=client(async jql=>{if(jql.includes('cf[12634]'))return page([initiative]);if(jql.startsWith('key in'))return page([raw('CPD-1','CPD','Epic'),raw('EMD-1','EMD','Epic')]);return page([])});const result=await acquireQ3Datasets(fake.value,credentials);expect(result.relationships.deliveryParentsFound).toBe(2);expect(result.relationships.deliveryParentsResolved).toBe(2)});
  it('deduplicates Features returned by expansion',async()=>{const initiative=raw('DSP-1','DSP','Iniciativa estratégica',{issuelinks:[polaris('CPD-1')]});const feature=raw('CPD-2','CPD','Feature',{parent:{key:'CPD-1'}});const fake=client(async jql=>{if(jql.includes('cf[12634]'))return page([initiative]);if(jql.startsWith('key in'))return page([raw('CPD-1','CPD','Epic')]);if(jql.includes('issuetype = Feature'))return page([feature,feature]);return page([])});const result=await acquireQ3Datasets(fake.value,credentials);expect(result.relationships.featuresFound).toBe(1)});
  it('isolates a relationship failure from completed portfolio',async()=>{const initiative=raw('DSP-1','DSP','Iniciativa estratégica',{issuelinks:[polaris('CPD-1')]});const fake=client(async jql=>{if(jql.includes('cf[12634]'))return page([initiative]);if(jql.startsWith('key in'))throw new Error('private');return page([])});const result=await acquireQ3Datasets(fake.value,credentials);expect(result.portfolio.status).toBe('COMPLETED');expect(result.relationships.status).toBe('PARTIAL');expect(result.relationships.unresolvedLinks).toBe(1)});
  it('enables Q3 from completed portfolio despite operational truncation',()=>{const portfolio={...normalizeIssue(raw('DSP-1'),'https://site'),datasetRole:'PORTFOLIO' as const,portfolioMembership:'DECLARED_Q3' as const};const operational={...normalizeIssue(raw('DSP-2','DSP'),'https://site'),datasetRole:'OPERATIONAL' as const};const snapshot={schemaVersion:2,semanticProfileVersion:Q3_PROFILE_VERSION,datasets:{portfolio:{status:'COMPLETED',profile:'DEUNA_Q3_PORTFOLIO',queryScope:'Q3',itemsProcessed:1,initiativesDetected:1,pagesProcessed:1,truncated:false,fieldsCoverage:100,warnings:[],queriedAt:'2026-08-03'},operational:{status:'PARTIAL',projects:['CPD'],itemsProcessed:500,pagesProcessed:5,truncated:true,warnings:[],queriedAt:'2026-08-03'},relationships:{status:'COMPLETED',initiativesExpanded:1,deliveryParentsFound:0,deliveryParentsResolved:0,featuresFound:0,controlsFound:0,unresolvedLinks:0,truncated:false,coverage:100,warnings:[],queriedAt:'2026-08-03'},fieldDiscovery:[],fieldSample:{}},organizationId:'org',snapshotId:'s',version:6,previousSnapshotId:null,syncMode:'FULL',source:'Jira Cloud',dataMode:'LIVE',startedAt:'2026-08-03',completedAt:'2026-08-03',status:'PARTIAL',projectsRequested:['DSP','CPD'],projectsAccessible:['DSP','CPD'],issuesProcessed:2,issuesChanged:2,pagesProcessed:6,truncated:true,coverage:100,warnings:[],checkpoint:'2026-08-03',correlationId:'safe',durationMs:1,items:[portfolio,operational],metrics:{} as SemanticJiraSnapshotRecord['metrics'],metadataVersion:'m',deltas:[],dataQuality:[]} as SemanticJiraSnapshotRecord;const overview=buildQ3Overview(snapshot);expect(overview.reconciliation.committedQ3).toBe(1);expect(overview.pulse.commitment.status).not.toBe('UNAVAILABLE');expect(overview.initiatives).toHaveLength(1)});
  it('keeps previous snapshots without datasets readable',()=>{const item=normalizeIssue(raw('DSP-1'),'https://site');const legacy={schemaVersion:2,organizationId:'org',snapshotId:'s',version:5,previousSnapshotId:null,syncMode:'FULL',source:'Jira Cloud',dataMode:'LIVE',startedAt:'2026-08-03',completedAt:'2026-08-03',status:'PARTIAL',projectsRequested:['DSP'],projectsAccessible:['DSP'],issuesProcessed:1,issuesChanged:1,pagesProcessed:1,truncated:true,coverage:50,warnings:[],checkpoint:'2026-08-03',correlationId:'safe',durationMs:1,items:[item],metrics:{} as SemanticJiraSnapshotRecord['metrics'],metadataVersion:'m',deltas:[],dataQuality:[]} as SemanticJiraSnapshotRecord;expect(buildQ3Overview(legacy).initiatives).toHaveLength(1)});
  it('never exposes summaries in acquisition summaries',async()=>{const result=await acquireQ3Datasets(client().value,credentials);expect(JSON.stringify({portfolio:result.portfolio,operational:result.operational,relationships:result.relationships,fieldDiscovery:result.fieldDiscovery,fieldSample:result.fieldSample})).not.toContain('Sensitive')});
});
