import {describe,expect,it} from 'vitest';
import {normalizeIssue} from '@/lib/jira/live';
import type {SemanticJiraSnapshotRecord} from '@/lib/jira/store';
import {Q3_PROFILE_VERSION} from '@/lib/q3/config';
import {buildQ3Overview,type Q3Initiative,type Q3Overview} from '@/lib/q3/model';
import {buildQ3ExecutiveDecisions,carryOverStatusOf,daysToTarget,replanningStatusOf,targetUrgency,type DecisionViewer} from '@/lib/q3/decisions';

const raw=(extra:Record<string,unknown>={})=>({key:'DSP-900',fields:{summary:'Nombre sensible',project:{key:'DSP'},issuetype:{name:'Iniciativa estratégica'},status:{name:'En desarrollo',statusCategory:{name:'In Progress'}},created:'2026-01-01',updated:'2026-08-01',labels:[],customfield_12634:[{name:'Q3'}],customfield_11944:'2026-09-15',customfield_11372:{value:'Personas'},...extra}});
const normalized=normalizeIssue(raw(),'https://jira.example');
const snapshot:SemanticJiraSnapshotRecord={schemaVersion:2,semanticProfileVersion:Q3_PROFILE_VERSION,organizationId:'org',snapshotId:'s11',version:11,previousSnapshotId:null,syncMode:'FULL',source:'Jira Cloud',dataMode:'LIVE',startedAt:'2026-08-21T10:00:00Z',completedAt:'2026-08-21T10:00:00Z',status:'COMPLETED',projectsRequested:['DSP'],projectsAccessible:['DSP'],issuesProcessed:1,issuesChanged:1,pagesProcessed:1,truncated:false,coverage:100,warnings:[],checkpoint:'2026-08-21',correlationId:'safe',durationMs:1,items:[normalized],metrics:{} as SemanticJiraSnapshotRecord['metrics'],metadataVersion:'m',deltas:[],dataQuality:[]};
const base=buildQ3Overview(snapshot);
const defaults:Partial<Q3Initiative>={targetDate:'2026-09-15',committedQ3:true,commitmentConfidence:'HIGH',stageConfidence:'HIGH',progressStatus:'AVAILABLE',featuresTotal:2,featuresCompleted:1,featureCompletionRatio:50,pipelineStage:'FEATURE_EXECUTION',riskGateStatus:'IN_PROGRESS',riskDomains:{total:5,approved:0,applicable:5},blocked:false,releaseApplicability:'NOT_YET_REQUIRED',release:'NO_RELEASE_EVIDENCE',carryOver:'NONE',quarterDateConflict:false,quarterConsistency:'CONSISTENT',reasonForDelay:null,replanningDeclared:null,previousTargetDate:null,targetDateChangeCount:0,lastTargetDateChangedAt:null,quarterChangeCount:0,lastQuarterChangedAt:null,hasReplanningEvidence:false,okrClassification:'ALIGNED_REFERENCE',deliveryApplicability:'REQUIRED',linkage:'LINKED',executiveStage:'BUILDING'};
const overview=(extra:Partial<Q3Initiative>={}):Q3Overview=>({...base,snapshot:{...base.snapshot,version:11,lastUpdated:'2026-08-21T10:00:00Z'},initiatives:[{...base.initiatives[0],...defaults,...extra}]});
const admin:DecisionViewer={role:'ADMIN',accessRole:'Executive',scope:'Organización'};
const signal=(extra:Partial<Q3Initiative>={})=>buildQ3ExecutiveDecisions(overview(extra),admin)[0];

describe('Q3 governed decision engine',()=>{
 it('calculates factual urgency from snapshot time',()=>{expect(daysToTarget('2026-08-20','2026-08-21T23:00:00Z')).toBe(-1);expect(targetUrgency(-1)).toBe('OVERDUE');expect(targetUrgency(14)).toBe('DUE_SOON');expect(targetUrgency(15)).toBe('ON_TIME');expect(targetUrgency(null)).toBe('NO_TARGET')});
 it('does not turn an overdue date alone into a Decision',()=>expect(signal({targetDate:'2026-08-20'})).toBeUndefined());
 it('does not turn administered carry-over into Attention automatically',()=>expect(signal({targetDate:'2026-08-14',carryOver:'CARRY_OVER',targetDateChangeCount:1,previousTargetDate:'2026-07-31',hasReplanningEvidence:true})).toMatchObject({classification:'OPERATIONAL_ACTION',carryOverStatus:'ADMINISTERED_CARRY_OVER'}));
 it('turns chronic Q1 Q2 Q3 carry-over into Attention',()=>expect(signal({carryOver:'CHRONIC_CARRY_OVER'})).toMatchObject({classification:'EXECUTIVE_ATTENTION',ruleId:'CHRONIC_CARRY_OVER'}));
 it('turns over 30 days and zero Features into Attention, not Decision',()=>expect(signal({targetDate:'2026-07-17',featureCompletionRatio:0,featuresCompleted:0,featuresTotal:1,pipelineStage:'NOT_STARTED',carryOver:'CARRY_OVER',targetDateChangeCount:1,hasReplanningEvidence:true})).toMatchObject({classification:'EXECUTIVE_ATTENTION',ruleId:'OVERDUE_NO_TECHNICAL_PROGRESS'}));
 it('requires explicit VP evidence for a Decision',()=>expect(signal({targetDate:'2026-08-14',featureCompletionRatio:100,featuresCompleted:2,pipelineStage:'RISK_GATE',reasonForDelay:'Pendiente aprobación. Bloqueo escalado a VP Cumplimiento.'})).toMatchObject({classification:'EXECUTIVE_DECISION',ruleId:'EXPLICIT_EXECUTIVE_ESCALATION',decisionOwnerRole:'VP / C-Level'}));
 it('does not reopen a decision already taken by C-Level',()=>expect(signal({reasonForDelay:'Despriorizado por C-Level',quarterDateConflict:true})).toMatchObject({classification:'DATA_QUALITY',ruleId:'DATE_QUARTER_CONFLICT'}));
 it('ensures every Decision has alternatives or explicit executive evidence',()=>{const d=signal({reasonForDelay:'Escalado a VP Cumplimiento'});expect(d.classification).toBe('EXECUTIVE_DECISION');expect(d.alternatives.length>=2||d.evidence.some(x=>x.metric==='Escalamiento ejecutivo')).toBe(true)});
 it('uses missing delay reason as Data Quality, never Decision',()=>expect(signal({targetDate:'2026-07-31'})).toMatchObject({classification:'DATA_QUALITY',ruleId:'OVERDUE_WITHOUT_CHANGE_REASON'}));
 it('uses changelog-derived history as replanning evidence',()=>{const x={...overview().initiatives[0],targetDateChangeCount:2,previousTargetDate:'2026-07-31',lastTargetDateChangedAt:'2026-08-01'};expect(replanningStatusOf(x)).toBe('REPLANNED_DATE');expect(carryOverStatusOf({...x,carryOver:'CARRY_OVER'},'REPLANNED_DATE')).toBe('ADMINISTERED_CARRY_OVER')});
 it('normalizes changelog history even without a manual reason',()=>{const x=normalizeIssue({...raw(),flowosGovernanceHistory:{previousTargetDate:'2026-07-31',targetDateChangeCount:1,lastTargetDateChangedAt:'2026-08-01T10:00:00Z',quarterChangeCount:0}},'x');expect(x.reasonForDelay.value).toBeNull();expect(x.hasReplanningEvidence).toBe(true);expect(x.targetDateChangeCount).toBe(1);expect(x.previousTargetDate.value).toBe('2026-07-31')});
 it('keeps a reprogrammed >30 day zero-Feature case as Attention',()=>expect(signal({targetDate:'2026-07-17',featureCompletionRatio:0,featuresCompleted:0,featuresTotal:1,pipelineStage:'NOT_STARTED',carryOver:'CARRY_OVER',targetDateChangeCount:1,hasReplanningEvidence:true})).toMatchObject({classification:'EXECUTIVE_ATTENTION'}));
 it('keeps a short administered carry-over operational',()=>expect(signal({targetDate:'2026-08-14',featureCompletionRatio:0,featuresCompleted:0,featuresTotal:1,pipelineStage:'NOT_STARTED',carryOver:'CARRY_OVER',targetDateChangeCount:1,hasReplanningEvidence:true})).toMatchObject({classification:'OPERATIONAL_ACTION'}));
 it('keeps normal Risk Gate work operational',()=>expect(signal({targetDate:'2026-07-31',featureCompletionRatio:100,featuresCompleted:2,pipelineStage:'RISK_GATE',riskGateStatus:'IN_PROGRESS',carryOver:'CARRY_OVER',targetDateChangeCount:1,hasReplanningEvidence:true})).toMatchObject({classification:'OPERATIONAL_ACTION',ruleId:'FEATURES_DONE_RISK_OPEN'}));
 it('requires positive production evidence before suppressing remaining work',()=>{expect(signal({sourceStatus:'Finalizada',administrativelyCompleted:true,featureCompletionRatio:100,featuresCompleted:2,riskGateStatus:'APPROVED',pipelineStage:'RELEASE_READINESS',releaseApplicability:'REQUIRED'})).toMatchObject({ruleId:'RISK_APPROVED_RELEASE_MISSING'});expect(signal({productionConfirmed:true,pipelineStage:'PRODUCTION',release:'PRODUCTION'})).toBeUndefined()});
 it('keeps Quarter/date conflict in Data Quality',()=>expect(signal({quarterDateConflict:true})).toMatchObject({classification:'DATA_QUALITY',ruleId:'DATE_QUARTER_CONFLICT'}));
 it('keeps UNKNOWN in Data Quality',()=>expect(signal({pipelineStage:'UNKNOWN',riskGateStatus:'UNKNOWN'})).toMatchObject({classification:'DATA_QUALITY',severity:'ATTENTION'}));
 it('sanitizes names, ids, links and escalation evidence for restricted scope',()=>{const d=buildQ3ExecutiveDecisions(overview({reasonForDelay:'Escalado a VP Cumplimiento'}),{role:'TEAM_USER',accessRole:'ReadOnly',scope:'Personas'})[0],text=JSON.stringify(d);expect(d).toMatchObject({initiativeName:'DSP-001',initiativeReference:'DSP-001',href:'/decisions'});expect(text).not.toContain('Nombre sensible');expect(text).not.toContain('DSP-900');expect(text).not.toContain('VP Cumplimiento');expect(text).not.toContain('customfield_')});
 it('returns no records to ReadOnly without scope',()=>expect(buildQ3ExecutiveDecisions(overview({blocked:true}),{role:'TEAM_USER',accessRole:'ReadOnly',scope:'Consulta'})).toEqual([]));
});
