import {describe,expect,it} from 'vitest';
import {buildSemanticMetrics,calculateDataQuality,resolveSemanticItems,type MetadataCache} from '@/lib/snapshot/live-engine';
import {classifyHierarchyLevel,normalizeIssue,normalizeJiraStatus} from '@/lib/jira/live';
const metadata:MetadataCache={source:'JIRA_SOFTWARE',version:'m1',capturedAt:'2026-08-01',projects:[],issueTypes:[],statuses:[],statusCategories:[],customFields:[],boards:[],sprints:[{id:'s1',startDate:'2026-07-01',endDate:'2026-07-14'}],versions:[],components:[],users:[],teams:[],warnings:[]};
const raw=(key:string,type='Historia',extra:Record<string,unknown>={})=>({key,fields:{summary:key,project:{key:'PAY'},issuetype:{id:'1',name:type},status:{name:'En progreso',statusCategory:{name:'In Progress'}},created:'2026-01-01T00:00:00Z',updated:'2026-01-02T00:00:00Z',labels:[],...extra}});
describe('Semantic Snapshot v2',()=>{
  it('preserves separate team fields and generic parent type',()=>{const item=normalizeIssue(raw('PAY-2','Subtarea',{parent:{key:'PAY-1',fields:{issuetype:{id:'9',name:'Feature'}}},customfield_10001:{name:'A'},customfield_11377:{name:'B'},customfield_11845:{name:'C'},customfield_11844:{name:'D'},customfield_10603:{name:'E'},customfield_11126:{name:'F'}}),'https://site');expect(item.schemaVersion).toBe(2);expect([item.jiraTeam.value,item.equipoDeuna.value,item.equipoEjecutor.value,item.equipoSolicitante.value,item.equipoHabilitador.value,item.tempoTeam.value]).toEqual(['A','B','C','D','E','F']);expect(item.parentKey.value).toBe('PAY-1');expect(item.parentIssueTypeName.value).toBe('Feature')});
  it('inherits team from parent and ancestor before marking a subtask missing',()=>{const feature=normalizeIssue(raw('PAY-1','Feature',{customfield_10001:{name:'Morpheus'}}),'https://site');const story=normalizeIssue(raw('PAY-2','Historia',{parent:{key:'PAY-1',fields:{issuetype:{name:'Feature'}}}}),'https://site');const sub=normalizeIssue(raw('PAY-3','Subtarea riesgos',{parent:{key:'PAY-2',fields:{issuetype:{name:'Historia'}}}}),'https://site');const items=resolveSemanticItems([feature,story,sub],metadata);expect(items[1].teamResolutionSource).toBe('PARENT');expect(items[2].teamResolutionSource).toBe('ANCESTOR');expect(items[2].resolvedTeam.value).toBe('Morpheus');expect(items[2].resolvedEco.value).toBe('ECO Habilitadores')});
  it('marks test items NOT_APPLICABLE when no team evidence exists',()=>{const [item]=resolveSemanticItems([normalizeIssue(raw('PAY-1','Test'),'https://site')],metadata);expect(item.teamApplicability).toBe('NOT_APPLICABLE');expect(item.teamResolutionSource).toBe('NOT_APPLICABLE')});
  it.each([['Idea','IDEA'],['Iniciativa estratégica','INITIATIVE'],['Epic','FEATURE'],['Historia','DELIVERY_ITEM'],['Subtarea riesgos','SUBTASK'],['Plan Release','CONTROL_ITEM'],['Test Execution','TEST_ITEM'],['Unknown type','UNKNOWN']])('maps hierarchy %s',((name,level)=>expect(classifyHierarchyLevel(name)).toBe(level)));
  it('classifies period from sprint and never treats updatedAt as commitment',()=>{const sprint=normalizeIssue(raw('PAY-1','Historia',{customfield_10020:[{id:'s1',name:'Q3',originBoardId:'1'}]}),'https://site');const activity=normalizeIssue(raw('PAY-2','Historia',{updated:'2026-08-02T00:00:00Z'}),'https://site');const items=resolveSemanticItems([sprint,activity],metadata);expect(items[0].periodClassification).toBe('IN_Q3_COMMITMENT');expect(items[1].periodClassification).toBe('ACTIVE_IN_Q3');expect(items[1].periodEvidence[0]).toContain('activity-only')});
  it('maps observed statuses and leaves undecided status UNMAPPED',()=>{expect(normalizeJiraStatus('Aprobación Smoke Test')).toBe('INTERNAL_TESTING');expect(normalizeJiraStatus('Gestión')).toBe('UNMAPPED')});
  it('reports semantic quality populations and keeps unsupported metrics unavailable',()=>{const items=resolveSemanticItems([normalizeIssue(raw('PAY-1'),'https://site'),normalizeIssue(raw('PAY-2','Test'),'https://site')],metadata);const quality=calculateDataQuality(items);expect(quality.find(x=>x.code==='TEAM_MISSING_REAL')?.applicablePopulation).toBe(1);const metrics=buildSemanticMetrics(items,{projectsAccessible:1,truncated:false,snapshotVersion:3,syncMode:'FULL'});expect(metrics.unavailable.cycleTime.status).toBe('UNAVAILABLE');expect(metrics.flowDistribution.DEVELOPMENT.applicablePopulation).toBe(1)});
});
