'use client';
import Link from 'next/link';import {useState} from 'react';import {CheckCircle2,Cloud,Database,RefreshCw,ShieldCheck,TriangleAlert} from 'lucide-react';import {organizationContext,integrations} from '@/lib/enterprise/data';import type {Integration} from '@/lib/enterprise/types';
export function OrganizationContextBar(){const [open,setOpen]=useState(false);return <div className="org-context"><button onClick={()=>setOpen(!open)} aria-expanded={open}><span className="org-logo">D</span><span><b>{organizationContext.organizationName}</b><small>{organizationContext.activeQuarter} · Día {organizationContext.quarterDay} de {organizationContext.quarterDays}</small></span></button><div className="org-health"><span>Salud organizacional <b>{organizationContext.health}%</b></span><span>Cobertura <b>{organizationContext.coverage}%</b></span><span className="connection-ok"><i/> Jira conectado</span><span className="mode-badge">{organizationContext.dataMode} DATA</span></div>{open&&<div className="connection-popover"><div className="between"><b>Conexiones</b><Link href="/admin/integrations">Abrir Integration Hub →</Link></div>{integrations.slice(0,6).map(item=><div className="connection-row" key={item.id}><span className={item.status==='CONNECTED'?'dot connected':'dot'}/><span>{item.name}</span><b>{item.status==='CONNECTED'?'Conectado':item.status==='DEGRADED'?'Degradado':'Listo para conectar'}</b></div>)}<small>Última sincronización: hace 2 minutos · {organizationContext.coverage}% cobertura · 2 advertencias</small></div>}</div>}
export function IntegrationCard({item}:{item:Integration}){const [detail,setDetail]=useState(false);return <article className="integration-card card"><div className="between"><span className="integration-icon"><Cloud/></span><span className={`integration-status s-${item.status.toLowerCase()}`}>{item.status.replaceAll('_',' ')}</span></div><h3>{item.name}</h3><p>{item.category}</p><div className="integration-metrics"><span><b>{item.coverage==null?'Datos insuficientes':`${item.coverage}%`}</b>Cobertura</span><span><b>{item.objects.toLocaleString('es-EC')}</b>Objetos</span><span><b>{item.errors}</b>Errores</span></div><small>{item.mode} · {item.frequency}</small><button onClick={()=>setDetail(!detail)}>{item.action}</button>{detail&&<div className="integration-detail"><b>Permisos requeridos</b><p>{item.permissions.join(' · ')}</p><b>Responsable</b><p>{item.owner}</p><small>Conexión demo; no se realizaron solicitudes externas.</small></div>}</article>}
export function AdminNav(){const groups=[['General',['Organización','Identidad visual','Periodos','Preferencias']],['Usuarios y acceso',['Usuarios','Roles','Permisos','Scopes','Auditoría de acceso']],['Integraciones',['Integration Hub','Centro de sincronización','Credenciales','Logs']],['Jira',['Proyectos','Issue Types','Jerarquía','Status Mapping','Custom Fields','Boards','Sprints','Releases']],['Datos y métricas',['Métricas','Umbrales','Cobertura','Calidad de datos','Snapshots','Retención']],['Gobierno',['Audit Log','Data Sources','Sync Runs','Errores','Alertas','Políticas']]];const links:Record<string,string>={'Integration Hub':'/admin/integrations','Centro de sincronización':'/admin/sync','Proyectos':'/admin/jira/projects','Status Mapping':'/admin/jira/status-mapping','Custom Fields':'/admin/jira/fields','Calidad de datos':'/admin/data-quality'};return <aside className="admin-nav">{groups.map(([title,items])=><section key={title as string}><b>{title}</b>{(items as string[]).map(item=><Link key={item} href={links[item]??'/admin'}>{item}</Link>)}</section>)}</aside>}
export function AdminShell({children}:{children:React.ReactNode}){return <div className="admin-layout"><AdminNav/><div>{children}</div></div>}
export function SyncStatus({status='COMPLETED'}:{status?:string}){return <span className={`sync-status s-${status.toLowerCase()}`}>{status==='COMPLETED'?<CheckCircle2/>:status==='PARTIAL'?<TriangleAlert/>:<RefreshCw/>}{status}</span>}
export function StrategicVisual({title,question,interpretation,children}:{title:string;question:string;interpretation:string;children:React.ReactNode}){return <article className="strategic-visual card"><div className="visual-head"><div><span className="eyebrow purple">VISUALIZACIÓN ESTRATÉGICA</span><h3>{title}</h3><p>{question}</p></div><ShieldCheck/></div>{children}<div className="visual-interpretation"><b>Interpretación</b>{interpretation}</div><small>Fuente: Snapshot Engine · Actualizado hace 2 minutos · 96% cobertura · <button>Ver evidencia</button></small></article>}
export function DataQualityItem({label,value,status,recommendation}:{label:string;value:string;status:string;recommendation:string}){return <article className="quality-item"><span className="integration-icon"><Database/></span><div><b>{label}</b><span>{value}</span><small>{recommendation}</small></div><span className={`integration-status s-${status.toLowerCase()}`}>{status.replaceAll('_',' ')}</span></article>}
