'use client';
import {useEffect,useState} from 'react';
import {AlertTriangle,CalendarDays,ChevronDown,ShieldCheck,Target} from 'lucide-react';
import type {Q3ExecutiveDecision} from '@/lib/q3/decisions';
type Decision=Q3ExecutiveDecision&{evidenceContext:{features:{completed:number;total:number}|null;riskGateStatus:string;riskDomains:{total:number;approved:number;applicable:number};previousTargetDate:string|null;targetDateChangeCount:number;quarterChangeCount:number}|null};
export interface DecisionCenterData{snapshot:{version:number;lastUpdated:string};source:string;decisions:Decision[]}
const stage:Record<string,string>={NOT_STARTED:'Sin iniciar',FEATURE_EXECUTION:'En ejecución',RISK_GATE:'Risk Gate',WAITING_OFFICIAL_APPROVAL:'Aprobación oficial',RELEASE_READINESS:'Preparación de Release',PRODUCTION:'Producción',UNKNOWN:'Sin evidencia'};
const replanning:Record<string,string>={REPLANNED_DATE_AND_QUARTER:'Fecha y trimestre replanificados',REPLANNED_DATE:'Fecha replanificada',REPLANNED_QUARTER:'Trimestre replanificado',NOT_REPLANNED:'Sin replanificación',REPLANNING_EVIDENCE_PARTIAL:'Evidencia parcial de replanificación',UNKNOWN:'Replanificación sin evidencia'};
const carry:Record<string,string>={ADMINISTERED_CARRY_OVER:'Carry-over administrado',CHRONIC_CARRY_OVER:'Carry-over crónico',UNKNOWN_CARRY_OVER:'Carry-over sin evidencia suficiente'};
const risk:Record<string,string>={NOT_STARTED:'Sin iniciar',IN_PROGRESS:'En curso',WAITING_OFFICIAL_APPROVAL:'Aprobación oficial pendiente',APPROVED:'Aprobado',BLOCKED:'Bloqueado',CANCELLED:'Cancelado',UNKNOWN:'Sin evidencia'};
const date=(value:string|null)=>value?new Intl.DateTimeFormat('es-EC',{day:'2-digit',month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(`${value.slice(0,10)}T00:00:00Z`)):'Sin fecha';
const deviation=(days:number|null)=>days===null?'Sin fecha objetivo':days<0?`${Math.abs(days)} días de atraso`:days===0?'Vence hoy':`${days} días restantes`;
const count=(n:number,singular:string,plural:string)=>`${n} ${n===1?singular:plural}`;
const dqSummary=(items:Decision[])=>({insufficient:items.filter(x=>x.ruleId==='INSUFFICIENT_EVIDENCE').length,conflicts:items.filter(x=>x.ruleId==='DATE_QUARTER_CONFLICT').length,overdue:items.filter(x=>x.ruleId==='OVERDUE_WITHOUT_CHANGE_REASON').length});
function Evidence({decision}:{decision:Decision}){const context=decision.evidenceContext;return <details className="dc-evidence"><summary>Ver evidencia <ChevronDown size={14}/></summary><div className="dc-evidence-grid">{context?.features&&<div><span>Features</span><b>{context.features.completed}/{context.features.total} completadas</b></div>}{context&&<div><span>Risk Gate</span><b>{risk[context.riskGateStatus]??'Sin evidencia'}</b>{context.riskDomains.total>0&&<small>{context.riskDomains.approved}/{context.riskDomains.total} dominios aprobados</small>}</div>}<div><span>Fecha objetivo</span><b>{date(decision.targetDate)}</b><small>{deviation(decision.daysToTarget)}</small></div>{carry[decision.carryOverStatus]&&<div><span>Carry-over</span><b>{carry[decision.carryOverStatus]}</b></div>}<div><span>Replanificación</span><b>{replanning[decision.replanningStatus]??'Sin evidencia'}</b></div>{decision.blocked&&<div><span>Bloqueo</span><b>Bloqueo vigente</b></div>}<div><span>Etapa actual</span><b>{stage[decision.pipelineStage]??'Sin evidencia'}</b></div>{context&&(context.targetDateChangeCount>0||context.quarterChangeCount>0)&&<div><span>Historial relevante</span><b>{context.targetDateChangeCount} cambios de fecha · {context.quarterChangeCount} de trimestre</b>{context.previousTargetDate&&<small>Fecha anterior: {date(context.previousTargetDate)}</small>}</div>}{decision.evidence.filter(item=>!['Fecha objetivo','Etapa'].includes(item.metric)).map((item,index)=><div key={`${item.metric}-${index}`}><span>{item.metric}</span><b>{item.value}</b></div>)}</div></details>}
function RequiredDecision({decision}:{decision:Decision}){return <article className="dc-required" data-testid="executive-decision"><div className="dc-required-head"><div><span className="dc-kicker"><Target size={14}/> Decisión requerida</span><h2>{decision.initiativeName}</h2><p>{decision.initiativeReference} · {decision.eco??'ECO sin evidencia'}</p></div><div className="dc-decision-meta"><span className={`dc-severity ${decision.severity.toLowerCase()}`}>{decision.severity==='CRITICAL'?'Crítica':'Alta prioridad'}</span><b>{stage[decision.pipelineStage]}</b><small>{date(decision.targetDate)} · {deviation(decision.daysToTarget)}</small></div></div><div className="dc-question-grid"><section><span>¿Qué está pasando?</span><p>{decision.reason}</p></section><section><span>¿Por qué importa?</span><p>{decision.impact}</p></section><section className="dc-action"><span>¿Qué se necesita decidir?</span><p>{decision.recommendedAction}</p></section></div><div className="dc-options"><h3>Alternativas</h3><div>{decision.alternatives.map((option,index)=><div key={option}><span>{index+1}</span><p>{option}</p></div>)}</div></div><div className="dc-owner"><ShieldCheck size={17}/><div><span>Responsable de la decisión</span><b>{decision.decisionOwnerRole}</b></div></div><Evidence decision={decision}/></article>}
function AttentionTable({items}:{items:Decision[]}){return <section className="dc-section" data-testid="executive-attention"><div className="dc-section-title"><div><span>Seguimiento SteerCo</span><h2>Requiere atención</h2></div><b>{items.length}</b></div>{items.length?<div className="dc-table-wrap"><table className="dc-table"><thead><tr><th>Iniciativa</th><th>ECO</th><th>Señal</th><th>Etapa</th><th>Fecha / desviación</th><th>Acción recomendada</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td data-label="Iniciativa"><strong>{item.initiativeName}</strong><small>{item.initiativeReference}</small></td><td data-label="ECO">{item.eco??'Sin evidencia'}</td><td data-label="Señal"><span className="dc-attention-signal"><AlertTriangle size={13}/>{item.reason}</span></td><td data-label="Etapa">{stage[item.pipelineStage]}</td><td data-label="Fecha"><b>{date(item.targetDate)}</b><small>{deviation(item.daysToTarget)}</small></td><td data-label="Acción">{item.recommendedAction}</td></tr>)}</tbody></table></div>:<div className="dc-empty">No existen situaciones que requieran seguimiento ejecutivo.</div>}</section>}
function CollapsedSection({title,count:total,description,children,testId}:{title:string;count:number;description:string;children:React.ReactNode;testId:string}){return <details className="dc-collapsed" data-testid={testId}><summary><div><span>{title}</span><b>{total} señales</b><p>{description}</p></div><ChevronDown size={18}/></summary><div className="dc-collapsed-body">{children}</div></details>}
export function DecisionCenterView({data}:{data:DecisionCenterData}){const decisions=data.decisions.filter(x=>x.classification==='EXECUTIVE_DECISION'),attention=data.decisions.filter(x=>x.classification==='EXECUTIVE_ATTENTION'),operational=data.decisions.filter(x=>x.classification==='OPERATIONAL_ACTION'),quality=data.decisions.filter(x=>x.classification==='DATA_QUALITY'),qualitySummary=dqSummary(quality);return <div className="decision-center-live"><header className="dc-hero"><div><div className="dc-live-row"><span>Q3 2026</span><b>LIVE</b></div><h1>Decision Center</h1><p className="dc-headline">{count(decisions.length,'decisión requiere','decisiones requieren')} intervención <i/> {count(attention.length,'situación requiere','situaciones requieren')} atención</p><p>FlowOS separa decisiones ejecutivas de acciones operativas y problemas de calidad de datos.</p></div><div className="dc-source"><CalendarDays size={17}/><div><span>Última actualización</span><b>{new Intl.DateTimeFormat('es-EC',{dateStyle:'medium',timeStyle:'short'}).format(new Date(data.snapshot.lastUpdated))}</b><small>Snapshot v{data.snapshot.version} · {data.source}</small></div></div></header><section className="dc-primary"><div className="dc-primary-title"><span>Intervención ejecutiva</span><h2>Decisión requerida</h2></div>{decisions.length?decisions.map(item=><RequiredDecision key={item.id} decision={item}/>):<div className="dc-no-decisions"><ShieldCheck size={24}/><div><h3>No hay decisiones ejecutivas pendientes</h3><p>El motor no encontró evidencia suficiente que requiera elección de VP o C-Level.</p></div></div>}</section><AttentionTable items={attention}/><div className="dc-secondary"><CollapsedSection title="Gestión operativa" count={operational.length} description="Situaciones que pueden resolverse dentro del flujo normal sin intervención ejecutiva." testId="operational-collapsed"><div className="dc-compact-list">{operational.map(item=><article key={item.id}><div><b>{item.initiativeName}</b><small>{item.initiativeReference} · {item.eco}</small></div><span>{stage[item.pipelineStage]}</span><p>{item.recommendedAction}</p></article>)}</div></CollapsedSection><CollapsedSection title="Calidad de datos" count={quality.length} description="Señales de evidencia que no pertenecen a la bandeja ejecutiva." testId="quality-collapsed"><div className="dc-quality-summary"><div><b>{qualitySummary.insufficient}</b><span>Trazabilidad insuficiente</span></div><div><b>{qualitySummary.conflicts}</b><span>Conflictos Quarter/fecha</span></div><div><b>{qualitySummary.overdue}</b><span>Atrasos sin motivo registrado</span></div></div></CollapsedSection></div></div>}
export function DecisionCenterLive(){const[data,setData]=useState<DecisionCenterData|null>(null),[error,setError]=useState(false);useEffect(()=>{document.body.classList.add('decision-center-page');fetch('/api/decisions').then(response=>response.json()).then(value=>{if(value.data)setData(value.data);else setError(true)}).catch(()=>setError(true));return()=>document.body.classList.remove('decision-center-page')},[]);if(error)return <div className="dc-state"><h1>Decision Center</h1><p>No fue posible recuperar la evidencia ejecutiva LIVE.</p></div>;if(!data)return <div className="dc-state"><span className="dc-loader"/><p>Cargando decisiones con evidencia LIVE…</p></div>;return <DecisionCenterView data={data}/>}
