import Link from 'next/link'; import type {Health} from '@/lib/types'; import {ArrowDownRight,ArrowUpRight,CheckCircle2,AlertTriangle,XCircle,HelpCircle,ExternalLink} from 'lucide-react';
export const HealthBadge=({status}:{status:Health|string})=>{const Icon=status==='HEALTHY'?CheckCircle2:status==='CRITICAL'?XCircle:status==='UNAVAILABLE'?HelpCircle:AlertTriangle;return <span className={`badge ${status.toLowerCase()}`}><Icon size={13}/>{status.replaceAll('_',' ')}</span>};
export function KpiCard({label,value,status='HEALTHY',trend='+2.4%',explanation,formula}:{label:string;value:string;status?:Health;trend?:string;explanation:string;formula:string}){return <article className="kpi card"><div className="between"><span className="eyebrow">{label}</span><HealthBadge status={status}/></div><strong>{value}</strong><div className={trend.startsWith('-')?'trend down':'trend'}>{trend.startsWith('-')?<ArrowDownRight/>:<ArrowUpRight/>}{trend} vs. anterior</div><p>{explanation}</p><details><summary>Cómo se calcula</summary><small>{formula} · Fuente: Jira Demo · {`31 jul, 09:42`}</small></details></article>}
export const Progress=({value}:{value:number})=><div className="progress" aria-label={`${value}%`}><i style={{width:`${Math.min(value,100)}%`}}/></div>;
export const SourceLink=({href}:{href:string})=><a className="source" href={href} target="_blank" rel="noreferrer">Ver origen <ExternalLink size={13}/></a>;
export function PageHeader({eyebrow,title,description,action}:{eyebrow:string;title:string;description:string;action?:React.ReactNode}){return <header className="pagehead"><div><div className="eyebrow purple">{eyebrow}</div><h1>{title}</h1><p>{description}</p></div>{action}</header>}
export const EmptyState=({title='No hay resultados'}:{title?:string})=><div className="empty"><HelpCircle/><b>{title}</b><span>Ajusta los filtros o verifica la cobertura de datos.</span></div>;
export function InsightCard({item,index}:{item:{title:string;evidence:string;impact:string;recommendation:string};index:number}){return <article className="insight card"><span className="insight-no">0{index+1}</span><div><h3>{item.title}</h3><p>{item.evidence}</p><div className="insight-meta"><span><b>Impacto</b>{item.impact}</span><span><b>Recomendación</b>{item.recommendation}</span></div></div></article>}
export const Pill=({children}:{children:React.ReactNode})=><span className="pill">{children}</span>;
export const NavLink=({href,children}:{href:string;children:React.ReactNode})=><Link href={href}>{children}</Link>;
