import type { Eco, Initiative, InitiativeStatus, InitiativeType } from './types';
import type { HistoricalSnapshot } from './types';
export const lastUpdated='31 jul 2026 · 09:42 UTC';
export const ecoNames=['Personas','Merchants','GTM','Habilitadores','Operaciones','Experiencia','Riesgos','Data','QA'];
export const teams=["Pay’s Genius",'Cashbusters',"The Night’s Watch",'White Walkers','VISA Pay','Merchenarios','Wizard Micro','CNBS','Agregador','DevOps','Infraestructura','Arquitectura','QA Core','Continuidad','Data Platform'];
const titles=['Wallet onboarding biométrico','Checkout inteligente','Pagos recurrentes','Motor antifraude v2','Tokenización VISA','Portal comercios 360','Conciliación automática','Observabilidad transaccional','Migración de secretos','Experiencia QR','Cashback personalizado','Core de límites','Optimización KYC','Recuperación de pagos','Lakehouse financiero','Disputas digitales','Autoservicio de comercios','Hardening Kubernetes','Segmentación clientes','Release sin fricción','Alertas de continuidad','Catálogo de APIs','Journey de activación','Gobierno de datos','Score de riesgo comercio','Notificaciones omnicanal','Deuda SDK móvil','Reportería regulatoria','SLO de plataforma','Pruebas sintéticas','Control de terceros','Expansión QR regional','Orquestador de campañas','Aprobación adaptativa','Bóveda de consentimientos','Forecast de liquidez'];
const statuses:InitiativeStatus[]=['IN_DELIVERY','RISK_APPROVAL','READY_FOR_RELEASE','BLOCKED','IN_QA','DISCOVERY','PRODUCTION','PRIORITIZED','INTERNAL_TESTING','MASSIFICATION','PLANNED','DONE'];
const types:InitiativeType[]=['STRATEGIC','OPERATIONAL','IMPROVEMENT','TECH_DEBT','REGULATORY_RISK'];
const stageNames=['Discovery','Priorización','Planning','DEV','QA','Riesgo','Release','Despliegue','Masificación','Producción'];
export const initiatives:Initiative[]=titles.map((name,i)=>{const status=statuses[i%statuses.length]; const current=Math.min(9,Math.max(0,['DISCOVERY','PRIORITIZED','PLANNED','IN_DELIVERY','READY_FOR_QA','IN_QA','RISK_APPROVAL','READY_FOR_RELEASE','DEPLOYMENT','INTERNAL_TESTING','MASSIFICATION','PRODUCTION','DONE'].indexOf(status)-1)); return {id:`FLOW-${String(i+1).padStart(3,'0')}`,name,type:types[i%5],eco:ecoNames[i%9],okr:i%7===0?undefined:`O${(i%5)+1} · ${['Crecimiento rentable','Confianza y seguridad','Experiencia simple','Escala operacional','Plataforma resiliente'][i%5]}`,impact:['+18% conversión','-25% fraude','-30% time-to-market','99.95% disponibilidad','Cumplimiento regulatorio'][i%5],status,sourceStatus:['In Progress','Risk Matrix','Ready CR','Blocked by Team','QA Validation'][i%5],progress:status==='DONE'?100:status==='PRODUCTION'?96:Math.min(90,18+(i*13)%75),target:`${String(5+(i*2)%24).padStart(2,'0')} ago 2026`,daysInStatus:2+(i*3)%27,team:i%11===0?undefined:teams[i%teams.length],supplier:i%4===0?'Kruger':i%6===0?'TCS':'Interno',capacity:13+(i*7)%55,dependencies:i%4,risk:i%10===0?'CRITICAL':i%4===0?'HIGH':i%3===0?'MEDIUM':'LOW',actionPlan:i%5===0,release:i%3===0?`CR-2026.${31+i}`:undefined,confidence:42+(i*11)%57,nextGate:stageNames[Math.min(9,current+1)],decision:i%4===0?'Escalar dependencia':'Mantener forecast',owner:['María V.','Carlos P.','Ana G.','Diego R.'][i%4],priority:i%9===0?'P0':i%3===0?'P1':'P2',sourceUrl:`https://deuna.atlassian.net/browse/FLOW-${i+1}`,stages:stageNames.map((s,n)=>({name:s,days:n<=current?2+(i+n*2)%12:0,state:n<current?'done':n===current?'current':'next'}))};});
export const ecos:Eco[]=ecoNames.map((name,i)=>({name,code:i<4?'ECO':'CoE',health:i===3?'CRITICAL':i%3===0?'WARNING':'HEALTHY',commitments:3+(i%4),progress:47+i*5,available:110+i*15,committed:i===3?195:100+i*14,consumed:80+i*12,wip:5+i,dependencies:2+(i*3)%9,risks:i%4,cycleTime:8+i,throughput:12+i*2,forecast:i===3?'At risk':i%3===0?'Watch':'On track'}));
export const dependencies=Array.from({length:12},(_,i)=>({id:`DEP-${i+1}`,initiative:initiatives[(i*2)%initiatives.length].name,requester:teams[i%teams.length],provider:teams[(i+4)%teams.length],required:`${10+i} ago`,age:4+i*2,status:['IDENTIFIED','NEGOTIATING','ACCEPTED','IN_PROGRESS','ESCALATED','DELIVERED'][i%6],impact:i%4===0?'CRITICAL':i%3===0?'HIGH':'MEDIUM',owner:['Luis M.','Sara C.','Andrés T.'][i%3]}));
export const risks=initiatives.filter((_,i)=>i%4===0).map((x,i)=>({id:`RSK-${100+i}`,initiative:x.name,factor:['Ciberseguridad','Continuidad','Datos personales','Terceros'][i%4],severity:i%5===0?'CRITICAL':i%2===0?'HIGH':'MEDIUM',status:i%3===0?'APPROVAL_PENDING':'OPEN',plan:i%2===0?'Vencido':'En curso',days:9+i*4}));
export const releases=initiatives.filter(x=>x.release).map((x,i)=>({id:x.release!,initiative:x.name,date:x.target,stage:['Plan Release','Aprobación','Smoke Test','Internal Testing','Masificación 50%'][i%5],score:48+(i*7)%49,blocked:i%4===0,controls:{Funcional:true,Técnico:i%3!==0,QA:i%4!==0,Arquitectura:true,Riesgo:i%4!==0,Seguridad:i%5!==0,Continuidad:i%2===0,Operación:i%3!==0}}));
export const users=[['Valentina C.','EXECUTIVE','Organización'],['Santiago M.','ECO_LEADER','Personas'],['Daniela P.','DELIVERY_LEADER','Delivery'],['Mateo R.','PRODUCT_LEADER','Portafolio'],['Camila A.','RISK_LEADER','Riesgos'],['Nicolás T.','TEAM_USER',"Pay’s Genius"],['Isabel G.','ADMIN','Organización']];

export const historicalSnapshots: HistoricalSnapshot[] = [
  {period:'2026-W28',grain:'WEEK',metrics:{cycleTime:16.8,leadTime:39.2,timeToDeploy:18.1,capacityUtilization:81,wip:54,blockedRate:9,riskApprovalTime:6.1,qaTime:5.1,sprintCompletion:88,deliveryConfidence:76,initiativesAtRisk:6,overdueActionPlans:2,openDependencies:7}},
  {period:'2026-W29',grain:'WEEK',metrics:{cycleTime:17.1,leadTime:40.4,timeToDeploy:18.9,capacityUtilization:83,wip:56,blockedRate:10,riskApprovalTime:7.2,qaTime:5.4,sprintCompletion:87,deliveryConfidence:74,initiativesAtRisk:7,overdueActionPlans:3,openDependencies:8}},
  {period:'2026-W30',grain:'WEEK',metrics:{cycleTime:17.8,leadTime:41.1,timeToDeploy:20.2,capacityUtilization:85,wip:58,blockedRate:11,riskApprovalTime:8.8,qaTime:5.8,sprintCompletion:86,deliveryConfidence:71,initiativesAtRisk:8,overdueActionPlans:3,openDependencies:9}},
  {period:'2026-W31',grain:'WEEK',metrics:{cycleTime:18.4,leadTime:42.1,timeToDeploy:21.6,capacityUtilization:87,wip:61,blockedRate:12,riskApprovalTime:11.0,qaTime:6.2,sprintCompletion:84,deliveryConfidence:68,initiativesAtRisk:9,overdueActionPlans:4,openDependencies:10}},
  {period:'2026-05',grain:'MONTH',metrics:{cycleTime:15.9,leadTime:37.4,timeToDeploy:17.2,capacityUtilization:78,wip:51,blockedRate:8,riskApprovalTime:5.9,qaTime:4.8,sprintCompletion:90,deliveryConfidence:79,initiativesAtRisk:5,overdueActionPlans:2,openDependencies:6}},
  {period:'2026-06',grain:'MONTH',metrics:{cycleTime:17.2,leadTime:40.0,timeToDeploy:19.1,capacityUtilization:83,wip:56,blockedRate:10,riskApprovalTime:7.5,qaTime:5.5,sprintCompletion:87,deliveryConfidence:74,initiativesAtRisk:7,overdueActionPlans:3,openDependencies:8}},
  {period:'2026-07',grain:'MONTH',metrics:{cycleTime:18.4,leadTime:42.1,timeToDeploy:21.6,capacityUtilization:87,wip:61,blockedRate:12,riskApprovalTime:11.0,qaTime:6.2,sprintCompletion:84,deliveryConfidence:68,initiativesAtRisk:9,overdueActionPlans:4,openDependencies:10}},
  {period:'2026-Q2',grain:'QUARTER',metrics:{cycleTime:15.8,leadTime:37.1,timeToDeploy:17.4,capacityUtilization:79,wip:52,blockedRate:8,riskApprovalTime:6.0,qaTime:4.9,sprintCompletion:89,deliveryConfidence:78,initiativesAtRisk:6,overdueActionPlans:2,openDependencies:7,strategicCapacity:42,technicalDebtCapacity:18}},
  {period:'2026-Q3',grain:'QUARTER',metrics:{cycleTime:18.4,leadTime:42.1,timeToDeploy:21.6,capacityUtilization:87,wip:61,blockedRate:12,riskApprovalTime:11.0,qaTime:6.2,sprintCompletion:84,deliveryConfidence:68,initiativesAtRisk:9,overdueActionPlans:4,openDependencies:10,strategicCapacity:48,technicalDebtCapacity:27}},
];
