import type { Evidence } from '@/lib/types';
import type { Confidence } from '@/lib/jira/live';
import type { InitiativeKind, PipelineStage, Q3Initiative, Q3Overview } from './model';

export const EXECUTIVE_DUE_SOON_DAYS = 14;
export const EXECUTIVE_STALLED_DAYS = 30;
export type DecisionClassification='EXECUTIVE_DECISION'|'EXECUTIVE_ATTENTION'|'OPERATIONAL_ACTION'|'DATA_QUALITY';
export type ExecutiveSeverity='CRITICAL'|'HIGH'|'ATTENTION';
export type TargetUrgency='ON_TIME'|'DUE_SOON'|'OVERDUE'|'NO_TARGET';
export type ReplanningStatus='NOT_REPLANNED'|'REPLANNED_QUARTER'|'REPLANNED_DATE'|'REPLANNED_DATE_AND_QUARTER'|'REPLANNING_EVIDENCE_PARTIAL'|'UNKNOWN';
export type CarryOverStatus='NOT_CARRY_OVER'|'ADMINISTERED_CARRY_OVER'|'CHRONIC_CARRY_OVER'|'UNKNOWN_CARRY_OVER';
export interface DecisionViewer{role:'ADMIN'|'EXECUTIVE'|'ECO_LEADER'|'DELIVERY_LEADER'|'PRODUCT_LEADER'|'RISK_LEADER'|'TEAM_USER';accessRole:'Executive'|'Delivery'|'Leadership'|'ReadOnly';scope:string}
export interface Q3ExecutiveDecision{id:string;classification:DecisionClassification;severity:ExecutiveSeverity;initiativeReference:string;initiativeName:string;eco:string|null;initiativeType:InitiativeKind;pipelineStage:PipelineStage;blocked:boolean;replanningStatus:ReplanningStatus;carryOverStatus:CarryOverStatus;urgency:TargetUrgency;reason:string;impact:string;recommendedAction:string;alternatives:string[];evidence:Evidence[];ruleId:string;decisionOwnerRole:string;targetDate:string|null;daysToTarget:number|null;confidence:Confidence;sourceSnapshotVersion:number;href:string}
type Candidate=Omit<Q3ExecutiveDecision,'id'|'initiativeReference'|'initiativeName'|'eco'|'initiativeType'|'pipelineStage'|'blocked'|'replanningStatus'|'carryOverStatus'|'urgency'|'targetDate'|'daysToTarget'|'sourceSnapshotVersion'|'href'>&{executiveEvidence?:boolean};
const DAY=86_400_000,SOURCE='FlowOS · Jira Cloud Semantic Snapshot v2';
const utc=(value:string)=>{const m=value.match(/^(\d{4})-(\d{2})-(\d{2})/);return m?Date.UTC(+m[1],+m[2]-1,+m[3]):null};
export function daysToTarget(target:string|null,reference:string){if(!target)return null;const a=utc(target),b=utc(reference);return a===null||b===null?null:Math.round((a-b)/DAY)}
export function targetUrgency(days:number|null,window=EXECUTIVE_DUE_SOON_DAYS):TargetUrgency{return days===null?'NO_TARGET':days<0?'OVERDUE':days<=window?'DUE_SOON':'ON_TIME'}
export function replanningStatusOf(x:Q3Initiative):ReplanningStatus{const date=x.targetDateChangeCount>0||Boolean(x.previousTargetDate),quarter=x.quarterChangeCount>0;if(date&&quarter)return'REPLANNED_DATE_AND_QUARTER';if(date)return'REPLANNED_DATE';if(quarter)return'REPLANNED_QUARTER';if(x.replanningDeclared===true||x.reasonForDelay||x.hasReplanningEvidence)return'REPLANNING_EVIDENCE_PARTIAL';return x.replanningDeclared===false?'NOT_REPLANNED':'UNKNOWN'}
export function carryOverStatusOf(x:Q3Initiative,r:ReplanningStatus):CarryOverStatus{if(['NONE','CROSS_QUARTER_PLANNED'].includes(x.carryOver))return'NOT_CARRY_OVER';if(x.carryOver==='CHRONIC_CARRY_OVER')return'CHRONIC_CARRY_OVER';const active=(x.featureCompletionRatio??0)>0||['BUILDING','REVIEW','RISK_GATE','BLOCKED'].includes(x.executiveStage);return r!=='UNKNOWN'&&r!=='NOT_REPLANNED'&&active?'ADMINISTERED_CARRY_OVER':'UNKNOWN_CARRY_OVER'}
const confidence=(x:Q3Initiative):Confidence=>{const v=[x.commitmentConfidence,x.stageConfidence];return v.includes('NONE')?'NONE':v.includes('LOW')?'LOW':v.includes('MEDIUM')||x.progressStatus==='PARTIAL'?'MEDIUM':'HIGH'};
const escalation=(reason:string|null)=>Boolean(reason&&/(escalad[oa]|requiere|pendiente).{0,50}(\bvp\b|vicepresid|c[- ]?level|comit[eé] ejecutivo)/i.test(reason));
const evidence=(o:Q3Overview,x:Q3Initiative,metric:string,value:string):Evidence=>({metric,value,entity:x.canonicalKey,period:'Q3',source:SOURCE,lastUpdated:o.snapshot.lastUpdated,coverage:100});
const candidate=(base:Omit<Candidate,'confidence'>,x:Q3Initiative):Candidate=>({...base,confidence:confidence(x)});

function evaluate(x:Q3Initiative,o:Q3Overview,u:TargetUrgency,days:number|null,carry:CarryOverStatus):Candidate|null{
 const e=(m:string,v:string)=>evidence(o,x,m,v),date=x.targetDate?[e('Fecha objetivo',x.targetDate)]:[];
 if(escalation(x.reasonForDelay)){const gate=x.featureCompletionRatio===100&&x.riskGateStatus!=='APPROVED';return candidate({classification:'EXECUTIVE_DECISION',severity:'HIGH',reason:gate?'Se requiere intervención ejecutiva para resolver una aprobación de cumplimiento que impide avanzar hacia Release.':'Existe evidencia explícita de escalamiento a liderazgo ejecutivo.',impact:gate?'El desarrollo está completo, pero el gate de cumplimiento impide avanzar en el pipeline.':'El compromiso requiere intervención fuera del flujo operativo normal.',recommendedAction:'Resolver el escalamiento ejecutivo y confirmar el compromiso resultante.',alternatives:gate?['Resolver o escalar la aprobación pendiente','Revisar el compromiso','Ajustar alcance o fecha si el bloqueo no puede resolverse']:['Resolver el escalamiento','Revisar el compromiso'],evidence:[e('Escalamiento ejecutivo',x.reasonForDelay??'Evidencia disponible'),e('Etapa',x.pipelineStage),...date],ruleId:'EXPLICIT_EXECUTIVE_ESCALATION',decisionOwnerRole:'VP / C-Level',executiveEvidence:true},x)}
 if(carry==='CHRONIC_CARRY_OVER')return candidate({classification:'EXECUTIVE_ATTENTION',severity:'HIGH',reason:'La iniciativa permanece comprometida a través de Q1, Q2 y Q3.',impact:'La continuidad del compromiso amerita seguimiento de SteerCo, sin implicar todavía una decisión formal.',recommendedAction:'Revisar avance, bloqueo y vigencia del compromiso en SteerCo.',alternatives:[],evidence:[e('Carry-over','Q1 + Q2 + Q3'),...date],ruleId:'CHRONIC_CARRY_OVER',decisionOwnerRole:'Leadership'},x);
 if(u==='OVERDUE'&&days!==null&&days < -EXECUTIVE_STALLED_DAYS&&x.featureCompletionRatio===0)return candidate({classification:'EXECUTIVE_ATTENTION',severity:'HIGH',reason:'La iniciativa supera 30 días de atraso sin avance técnico en Features.',impact:'El compromiso requiere revisión de SteerCo, aunque no existe evidencia para imponer una decisión específica.',recommendedAction:'Validar si el compromiso conserva alcance, fecha y prioridad vigentes.',alternatives:[],evidence:[e('Features',`0/${x.featuresTotal} completadas`),...date],ruleId:'OVERDUE_NO_TECHNICAL_PROGRESS',decisionOwnerRole:'Leadership'},x);
 const structural=x.blocked&&(carry!=='NOT_CARRY_OVER'||x.featureCompletionRatio===100||x.riskGateStatus==='BLOCKED');
 if(structural)return candidate({classification:'EXECUTIVE_ATTENTION',severity:'HIGH',reason:'Existe un bloqueo estructural que mantiene detenido el pipeline.',impact:'El bloqueo amerita seguimiento transversal, pero no contiene evidencia suficiente para exigir una decisión formal.',recommendedAction:'Escalar seguimiento del bloqueo y confirmar responsable y plan de resolución.',alternatives:[],evidence:[e('Bloqueo','Evidencia estructurada'),e('Etapa',x.pipelineStage),...date],ruleId:'STRUCTURAL_BLOCKED_COMMITMENT',decisionOwnerRole:'Leadership'},x);
 if(x.blocked)return candidate({classification:'OPERATIONAL_ACTION',severity:'ATTENTION',reason:'Existe un bloqueo dentro del flujo operativo normal.',impact:'El trabajo no puede avanzar hasta resolver el bloqueo.',recommendedAction:'Resolver el bloqueo y actualizar su evidencia.',alternatives:[],evidence:[e('Bloqueo','Sí'),...date],ruleId:'BLOCKED_COMMITMENT',decisionOwnerRole:'Delivery'},x);
 if(x.featureCompletionRatio===100&&!['APPROVED','CANCELLED'].includes(x.riskGateStatus))return candidate({classification:x.riskGateStatus==='BLOCKED'?'EXECUTIVE_ATTENTION':'OPERATIONAL_ACTION',severity:x.riskGateStatus==='BLOCKED'?'HIGH':'ATTENTION',reason:'El desarrollo terminó, pero el Risk Gate todavía no está aprobado.',impact:'La iniciativa no puede avanzar a readiness de Release mientras el Risk Gate permanezca abierto.',recommendedAction:'Completar el Risk Gate antes de preparar Release.',alternatives:[],evidence:[e('Features',`${x.featuresCompleted}/${x.featuresTotal} completadas`),e('Risk Gate',x.riskGateStatus),...date],ruleId:'FEATURES_DONE_RISK_OPEN',decisionOwnerRole:'Riesgos'},x);
 if(x.riskGateStatus==='WAITING_OFFICIAL_APPROVAL')return candidate({classification:'OPERATIONAL_ACTION',severity:'ATTENTION',reason:'La iniciativa espera aprobación oficial dentro del flujo normal.',impact:'La aprobación pendiente aún no habilita Release.',recommendedAction:'Dar seguimiento operativo a la aprobación oficial.',alternatives:[],evidence:[e('Risk Gate','Aprobación oficial pendiente'),...date],ruleId:'OFFICIAL_APPROVAL_WAITING',decisionOwnerRole:'Riesgos'},x);
 if(x.featureCompletionRatio===100&&x.riskGateStatus==='APPROVED'&&x.releaseApplicability==='REQUIRED'&&x.release==='NO_RELEASE_EVIDENCE')return candidate({classification:'OPERATIONAL_ACTION',severity:'ATTENTION',reason:'El Risk Gate está aprobado y el Release requerido aún no tiene evidencia.',impact:'La iniciativa permanece en readiness de Release; no existe evidencia positiva de Producción.',recommendedAction:'Preparar y evidenciar el Release.',alternatives:[],evidence:[e('Risk Gate','Aprobado'),e('Release','Sin evidencia'),...date],ruleId:'RISK_APPROVED_RELEASE_MISSING',decisionOwnerRole:'Delivery'},x);
 if(x.pipelineStage==='PRODUCTION')return null;
 if(u==='OVERDUE'&&carry==='ADMINISTERED_CARRY_OVER')return candidate({classification:'OPERATIONAL_ACTION',severity:'ATTENTION',reason:'La fecha está vencida, pero existe evidencia de replanificación y gestión activa.',impact:'El carry-over se encuentra administrado dentro del flujo actual.',recommendedAction:'Mantener seguimiento operativo al plan reprogramado.',alternatives:[],evidence:[e('Carry-over','Administrado'),...date],ruleId:'ADMINISTERED_CARRY_OVER',decisionOwnerRole:'Delivery'},x);
 if(u==='OVERDUE'&&days!==null&&days < -EXECUTIVE_DUE_SOON_DAYS&&!x.reasonForDelay)return{classification:'DATA_QUALITY',severity:'ATTENTION',reason:'La fecha lleva más de 14 días vencida y no existe motivo de cambio disponible.',impact:'No es posible distinguir atraso operativo de replanificación no documentada.',recommendedAction:'Completar o reconciliar la evidencia de replanificación.',alternatives:[],evidence:[...date,e('Motivo de cambio','Sin evidencia')],ruleId:'OVERDUE_WITHOUT_CHANGE_REASON',decisionOwnerRole:'Data Steward',confidence:'LOW'};
 if(x.quarterDateConflict)return{classification:'DATA_QUALITY',severity:'ATTENTION',reason:'La fecha objetivo no es consistente con el Quarter declarado.',impact:'La evidencia temporal debe reconciliarse antes de evaluar el compromiso.',recommendedAction:'Reconciliar Quarter y fecha objetivo en la fuente canónica.',alternatives:[],evidence:[e('Consistencia temporal',x.quarterConsistency),...date],ruleId:'DATE_QUARTER_CONFLICT',decisionOwnerRole:'Data Steward',confidence:'MEDIUM'};
 const missing=[x.pipelineStage==='UNKNOWN'?'etapa':null,x.riskGateStatus==='UNKNOWN'?'Risk Gate':null,x.progressStatus==='UNAVAILABLE'?'Features':null,u==='NO_TARGET'?'fecha objetivo':null,x.deliveryApplicability==='REQUIRED'&&x.linkage==='NO_DELIVERY_LINK'?'vínculo Delivery':null,x.okrClassification==='NO_REFERENCE'?'trazabilidad OKR':null].filter((v):v is string=>Boolean(v));
 return missing.length?{classification:'DATA_QUALITY',severity:'ATTENTION',reason:`La evidencia es insuficiente para determinar ${missing.join(', ')}.`,impact:'La incertidumbre limita la lectura ejecutiva, pero no demuestra un incumplimiento.',recommendedAction:'Completar o reconciliar la evidencia faltante.',alternatives:[],evidence:[e('Evidencia faltante',missing.join(', '))],ruleId:'INSUFFICIENT_EVIDENCE',decisionOwnerRole:'Data Steward',confidence:'LOW'}:null;
}

const canNames=(v:DecisionViewer)=>v.role==='ADMIN'||['Executive','Leadership','Delivery'].includes(v.accessRole);
const allowed=(o:Q3Overview,v:DecisionViewer)=>v.scope==='Organización'||v.scope==='Delivery'?o.initiatives:o.initiatives.filter(x=>x.eco===v.scope);
export function buildQ3ExecutiveDecisions(o:Q3Overview,v:DecisionViewer,options:{dueSoonDays?:number}={}):Q3ExecutiveDecision[]{const window=options.dueSoonDays??EXECUTIVE_DUE_SOON_DAYS,names=canNames(v);return allowed(o,v).filter(x=>x.committedQ3).map((x,index)=>{const days=daysToTarget(x.targetDate,o.snapshot.lastUpdated),urgency=targetUrgency(days,window),replanningStatus=replanningStatusOf(x),carryOverStatus=carryOverStatusOf(x,replanningStatus);let c=evaluate(x,o,urgency,days,carryOverStatus);if(!c)return null;if(c.classification==='EXECUTIVE_DECISION'&&c.alternatives.length<2&&!c.executiveEvidence)c={...c,classification:'EXECUTIVE_ATTENTION',severity:'HIGH'};const safe=`DSP-${String(index+1).padStart(3,'0')}`,reference=names?x.canonicalKey:safe,rest={...c};delete rest.executiveEvidence;return{...rest,id:`Q3-${o.snapshot.version}-${reference}-${c.ruleId}`,initiativeReference:reference,initiativeName:names?x.summary:safe,eco:x.eco,initiativeType:x.initiativeType,pipelineStage:x.pipelineStage,blocked:x.blocked,replanningStatus,carryOverStatus,urgency,targetDate:x.targetDate,daysToTarget:days,sourceSnapshotVersion:o.snapshot.version,href:names?`/initiatives/${encodeURIComponent(x.canonicalKey)}`:'/decisions',evidence:c.evidence.map(entry=>({...entry,entity:reference,value:names||entry.metric!=='Escalamiento ejecutivo'?entry.value:'Evidencia disponible'}))}}).filter((x):x is Q3ExecutiveDecision=>x!==null)}
export function decisionTotals(d:Q3ExecutiveDecision[]){const c:DecisionClassification[]=['EXECUTIVE_DECISION','EXECUTIVE_ATTENTION','OPERATIONAL_ACTION','DATA_QUALITY'];return Object.fromEntries(c.map(k=>[k,d.filter(x=>x.classification===k).length])) as Record<DecisionClassification,number>}
