import type {JiraCloudClient} from '@/lib/jira/client';
import type {FlowOsWorkItem} from '@/lib/jira/live';
import {CUSTOM_FIELDS} from '@/lib/jira/live';
import type {JiraSnapshotRecord} from '@/lib/jira/store';

export type EnterpriseSource='JIRA_SOFTWARE'|'JSM'|'JIRA_PRODUCT_DISCOVERY'|'COMPASS'|'ASSETS'|'CONFLUENCE'|'ROVO';
export interface MetadataCache{source:EnterpriseSource;version:string;capturedAt:string;projects:Record<string,unknown>[];issueTypes:Record<string,unknown>[];statuses:Record<string,unknown>[];statusCategories:Record<string,unknown>[];customFields:Record<string,unknown>[];boards:Record<string,unknown>[];sprints:Record<string,unknown>[];versions:Record<string,unknown>[];components:Record<string,unknown>[];users:Record<string,unknown>[];teams:string[];warnings:string[]}
export type DeltaKind='NEW_RISK'|'STATUS_CHANGED'|'STORY_POINTS_CHANGED'|'SPRINT_CHANGED'|'OWNER_CHANGED'|'PRIORITY_CHANGED'|'ETA_CHANGED'|'ISSUE_CREATED';
export interface SnapshotDelta{issueKey:string;kind:DeltaKind;before:string|number|null;after:string|number|null}
export interface HistoricalMetric{name:'Cycle Time'|'Lead Time'|'Flow Efficiency'|'Blocked Time'|'WIP'|'Throughput'|'Predictability'|'SLA';value:number|null;unit:string;evidence:string}
export interface QualityFinding{rule:string;count:number;issueKeys:string[]}

const text=(value:unknown)=>value==null?null:String(value);
export function mergeIncremental(previous:FlowOsWorkItem[],changed:FlowOsWorkItem[]){return [...new Map([...previous,...changed].map(item=>[item.sourceKey,item])).values()]}
export function calculateDeltas(previous:FlowOsWorkItem[],current:FlowOsWorkItem[]):SnapshotDelta[]{const old=new Map(previous.map(x=>[x.sourceKey,x]));const deltas:SnapshotDelta[]=[];const compare:Array<[keyof FlowOsWorkItem,DeltaKind]>=[['sourceStatus','STATUS_CHANGED'],['storyPoints','STORY_POINTS_CHANGED'],['sprint','SPRINT_CHANGED'],['owner','OWNER_CHANGED'],['priority','PRIORITY_CHANGED'],['eta','ETA_CHANGED']];for(const item of current){const before=old.get(item.sourceKey);if(!before){deltas.push({issueKey:item.sourceKey,kind:'ISSUE_CREATED',before:null,after:item.sourceStatus});if(['HIGH','CRITICAL'].includes((item.riskLevel??'').toUpperCase()))deltas.push({issueKey:item.sourceKey,kind:'NEW_RISK',before:null,after:item.riskLevel});continue}for(const [field,kind] of compare){if(text(before[field])!==text(item[field]))deltas.push({issueKey:item.sourceKey,kind,before:text(before[field]),after:text(item[field])})}if(!['HIGH','CRITICAL'].includes((before.riskLevel??'').toUpperCase())&&['HIGH','CRITICAL'].includes((item.riskLevel??'').toUpperCase()))deltas.push({issueKey:item.sourceKey,kind:'NEW_RISK',before:before.riskLevel,after:item.riskLevel})}return deltas}
export function calculateDataQuality(items:FlowOsWorkItem[]):QualityFinding[]{const rules:[string,(x:FlowOsWorkItem)=>boolean][]=[['Sin responsable',x=>!x.owner],['Sin Story Points',x=>x.storyPoints===null],['Sin Epic',x=>!x.epic],['Sin Initiative',x=>!x.initiative],['Sin Sprint',x=>!x.sprint],['Sin Due Date',x=>!x.eta],['Sin Team',x=>!x.team],['Sin ECO',x=>!x.eco]];return rules.map(([rule,test])=>{const issueKeys=items.filter(test).map(x=>x.sourceKey);return {rule,count:issueKeys.length,issueKeys}})}
export function calculateHistoricalMetrics(items:FlowOsWorkItem[],previous:JiraSnapshotRecord|null,deltas:SnapshotDelta[]):HistoricalMetric[]{const resolved=items.filter(x=>x.createdAt&&x.resolutionDate);const lead=resolved.map(x=>(new Date(x.resolutionDate!).getTime()-new Date(x.createdAt!).getTime())/86400000).filter(Number.isFinite);const avg=lead.length?Math.round(lead.reduce((a,b)=>a+b,0)/lead.length*10)/10:null;const wip=items.filter(x=>!['DONE','PRODUCTION','CANCELLED'].includes(x.normalizedStatus)).length;const throughput=items.filter(x=>x.resolutionDate&&(!previous||x.resolutionDate>previous.completedAt)).length;const changedStatus=deltas.filter(x=>x.kind==='STATUS_CHANGED').length;return [{name:'Cycle Time',value:null,unit:'days',evidence:'Requiere changelog de transiciones.'},{name:'Lead Time',value:avg,unit:'days',evidence:lead.length?`${lead.length} issues con created y resolutiondate.`:'Sin issues resueltos con fechas completas.'},{name:'Flow Efficiency',value:null,unit:'%',evidence:'Requiere tiempos activos y de espera del changelog.'},{name:'Blocked Time',value:null,unit:'days',evidence:'Requiere historial de entrada y salida de estados bloqueados.'},{name:'WIP',value:wip,unit:'issues',evidence:`${items.length} issues observados en el snapshot.`},{name:'Throughput',value:throughput,unit:'issues',evidence:previous?'Resoluciones posteriores al checkpoint anterior.':'Primera captura; valor provisional.'},{name:'Predictability',value:null,unit:'%',evidence:'Requiere compromisos de sprint y cierres históricos.'},{name:'SLA',value:null,unit:'%',evidence:'Requiere configuración SLA de JSM.'}].map(metric=>metric.name==='WIP'&&changedStatus===0&&!items.length?{...metric,value:null}:metric) as HistoricalMetric[]}

async function optional<T>(operation:()=>Promise<{data:T}>,label:string,warnings:string[],fallback:T){try{return (await operation()).data}catch{warnings.push(`${label}: INACCESSIBLE`);return fallback}}
export async function buildMetadataCache(client:JiraCloudClient,projects:string[]):Promise<MetadataCache>{const warnings:string[]=[];const [projectPage,issueTypes,statuses,fields,users]=await Promise.all([client.getProjects(),optional(()=>client.getIssueTypes(),'Issue Types',warnings,[]),optional(()=>client.getStatuses(),'Statuses',warnings,[]),optional(()=>client.getFields(),'Custom Fields',warnings,[]),optional(()=>client.getUsers(),'Users',warnings,[])]);const selected=projectPage.items.filter(p=>projects.includes(String(p.key)));const boards:Record<string,unknown>[]=[],sprints:Record<string,unknown>[]=[],versions:Record<string,unknown>[]=[],components:Record<string,unknown>[]=[];for(const project of selected){const key=String(project.key);const projectBoards=await optional(()=>client.getBoards(key),`Boards ${key}`,warnings,{values:[]});boards.push(...projectBoards.values);versions.push(...await optional(()=>client.getVersions(key),`Versions ${key}`,warnings,[]));components.push(...await optional(()=>client.getComponents(key),`Components ${key}`,warnings,[]))}for(const board of boards){sprints.push(...(await optional(()=>client.getSprints(String(board.id)),`Sprints board ${String(board.id)}`,warnings,{values:[]})).values)}const statusCategories=[...new Map(statuses.map(status=>{const category=(status.statusCategory??{}) as Record<string,unknown>;return [String(category.id??category.key??'unknown'),category]})).values()];const customFields=fields.filter(field=>CUSTOM_FIELDS.includes(String(field.id) as typeof CUSTOM_FIELDS[number]));const teams=[...new Set(customFields.filter(field=>/team|equipo/i.test(String(field.name))).map(field=>String(field.name)))];return {source:'JIRA_SOFTWARE',version:crypto.randomUUID(),capturedAt:new Date().toISOString(),projects:selected,issueTypes,statuses,statusCategories,customFields,boards,sprints,versions,components,users,teams,warnings}}
