import type {Integration,OrganizationContext,SyncRun} from './types';
export const organizationContext:OrganizationContext={organizationId:'org-deuna-ecuador',organizationName:'Deuna Ecuador',businessUnit:'Enterprise Execution',country:'Ecuador',timezone:'America/Guayaquil',fiscalYear:2026,activeQuarter:'Q3 2026',quarterStart:'2026-07-01',quarterEnd:'2026-09-30',quarterDay:41,quarterDays:65,dataMode:'DEMO',lastSync:'2026-07-31T09:40:00Z',syncHealth:'HEALTHY',health:84,coverage:96,connectedSources:['Jira Software','Jira Product Discovery','Jira Risk Project','Jira Releases']};
const connected=['Jira Software','Jira Product Discovery','Jira Service Management','Jira Releases','Jira Risk Project'];
export const integrations:Integration[]=['Jira Software','Jira Product Discovery','Jira Service Management','Jira Releases','Jira Risk Project','Confluence','Compass','Assets','Tempo','Xray','ScriptRunner','Rovo','Azure DevOps','Power BI'].map((name,index)=>({id:name.toLowerCase().replaceAll(' ','-'),name,category:index<5?'Atlassian Work Management':index<12?'Atlassian Ecosystem':'Business Intelligence',status:connected.includes(name)?(name==='Jira Service Management'?'DEGRADED':'CONNECTED'):index<10?'READY_TO_CONNECT':'NOT_CONFIGURED',mode:index<5?'READ_ONLY':index<12?'CONFIGURATION_ONLY':'PLANNED',lastSync:connected.includes(name)?'2026-07-31T09:40:00Z':undefined,coverage:connected.includes(name)?(name==='Jira Service Management'?78:96):undefined,errors:name==='Jira Service Management'?2:0,objects:connected.includes(name)?1200+index*417:0,permissions:['read:jira-work','read:jira-user'],frequency:connected.includes(name)?'Cada 15 minutos':'No configurada',owner:index<5?'Platform Engineering':'Por asignar',action:connected.includes(name)?'Ver detalle':'Configurar',demo:true}));
export const syncRuns:SyncRun[]=[
{id:'SYNC-240731-0940',organizationId:'org-deuna-ecuador',mode:'INCREMENTAL',status:'COMPLETED',startedAt:'2026-07-31T09:39:14Z',completedAt:'2026-07-31T09:40:02Z',checkpoint:'2026-07-31T09:38:59Z',processed:2484,changed:46,errors:0,coverage:96,sources:connected,durationSeconds:48,correlationId:'corr-a7f3'},
{id:'SYNC-240731-0925',organizationId:'org-deuna-ecuador',mode:'INCREMENTAL',status:'PARTIAL',startedAt:'2026-07-31T09:24:12Z',completedAt:'2026-07-31T09:25:33Z',checkpoint:'2026-07-31T09:23:59Z',processed:2410,changed:31,errors:2,coverage:91,sources:connected,durationSeconds:81,correlationId:'corr-99b2'},
{id:'SYNC-240730-2100',organizationId:'org-deuna-ecuador',mode:'SCHEDULED',status:'COMPLETED',startedAt:'2026-07-30T21:00:00Z',completedAt:'2026-07-30T21:03:41Z',checkpoint:'2026-07-30T20:59:59Z',processed:8921,changed:218,errors:0,coverage:96,sources:connected,durationSeconds:221,correlationId:'corr-8c11'}];
export const projects=Array.from({length:12},(_,i)=>({id:`PRJ-${i+1}`,key:['JPD','PAY','WAL','MER','RISK','REL','PLAT','DATA','QA','OPS','JSM','ARCH'][i],name:['Product Discovery','Payments Core','Wallet Experience','Merchant Platform','Risk Management','Release Control','Platform Enablement','Data Platform','Quality Engineering','Operations','Service Management','Architecture'][i],type:['PRODUCT_DISCOVERY','DELIVERY','DELIVERY','DELIVERY','RISK','RELEASE','TECHNICAL','TECHNICAL','SUPPORT','OPERATIONS','SERVICE_MANAGEMENT','TECHNICAL'][i],eco:['GTM','Personas','Personas','Merchants','Riesgos','Operaciones','Habilitadores','Data','QA','Operaciones','Operaciones','Habilitadores'][i],included:i!==10,coverage:i===10?64:92+i%5,lastSync:'Hace 2 minutos'}));
export const statusMappings=['Idea','To Do','Selected for Development','In Progress','Blocked','Ready for QA','Testing','Risk Matrix','Ready CR','Deploying','Internal Testing','Massification','Production','Done'].map((source,i)=>({source,sourceId:`status-${100+i}`,target:['DISCOVERY','PLANNED','PRIORITIZED','IN_DELIVERY','BLOCKED','READY_FOR_QA','IN_QA','RISK_APPROVAL','READY_FOR_RELEASE','DEPLOYMENT','INTERNAL_TESTING','MASSIFICATION','PRODUCTION','DONE'][i],critical:['In Progress','Risk Matrix','Production'].includes(source),mapped:i<12}));
export const fieldMappings=['Story Points','Team','Sprint','Flagged','Target Start','Target End','OKR','Initiative Type','ECO','Risk','Risk Factor','Action Plan','Release','DEV Start','DEV End','QA Start','QA End','Deployment Start','Production Date','Supplier','Capacity','Priority','Confidence'].map((concept,i)=>({concept,jiraName:i<6?concept:`Deuna ${concept}`,fieldId:i<6?`system.${concept.toLowerCase().replaceAll(' ','_')}`:`customfield_${10100+i}`,type:i%4===0?'number':i%3===0?'date':'text',example:i%4===0?'21':i%3===0?'2026-07-18':`Ejemplo ${concept}`,required:['Team','OKR','ECO','Risk','Production Date'].includes(concept),coverage:i%7===0?null:74+(i%6)*4,status:i%7===0?'INSUFFICIENT_DATA':i%5===0?'WARNING':'GOOD',suggestion:`Coincidencia determinística por nombre y tipo` }));
